version: 2.1
jobs:
  install:
    parameters:
      python-version:
        type: string
    working_directory: ~/project
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Set python << parameters.python-version >>
          command: |
            pyenv global << parameters.python-version >>
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - machine-<< parameters.python-version >>-{{ checksum "dev_requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r dev_requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: machine-<< parameters.python-version >>-{{ checksum "dev_requirements.txt" }}
  lint:
    working_directory: ~/project
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Set python 3.7
          command: |
            pyenv global 3.7
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      - restore_cache:
          key: machine-3.7-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run pylint
          command: |
            . venv/bin/activate
            pylint easyfsl
      - store_artifacts:
          path: lint-project-reports
          destination: lint-project-reports

workflows:
  main:
    jobs:
      - install:
          matrix:
            parameters:
              python-version: ["3.6", "3.7", "3.8"]
      - lint:
          requires:
            - install
