version: 2
jobs:
  install-3.7:
    working_directory: ~/project
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Set python 3.7.0
          command: |
            pyenv global 3.7.0
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - machine-3.7-{{ checksum "dev_requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r dev_requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: machine-3.7-{{ checksum "dev_requirements.txt" }}
  tests-3.7:
    working_directory: ~/project
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Set python 3.7.0
          command: |
            pyenv global 3.7.0
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      - restore_cache:
          key: machine-3.7-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run pytest
          command: |
            . venv/bin/activate
            make test
  lint-3.7:
    working_directory: ~/project
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Set python 3.7.0
          command: |
            pyenv global 3.7.0
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      - restore_cache:
          key: machine-3.7-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run pylint
          command: |
            . venv/bin/activate
            make lint
      - store_artifacts:
          path: lint-project-reports
          destination: lint-project-reports

workflows:
  version: 2
  main:
    jobs:
      - install-3.7
      # - tests-3.7:
      #     requires:
      #       - install-3.7
      - lint-3.7:
          requires:
            - install-3.7
